import json
import uuid
from pathlib import Path

from flask import current_app, has_app_context
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing, String
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.extensions import db
from app.models import AnalysisReport, Case, FinalReport, User


def _latest_analysis(case_id):
    return (
        AnalysisReport.query.filter_by(case_id=case_id)
        .order_by(AnalysisReport.created_at.desc())
        .first()
    )


def _safe_json(raw, fallback):
    try:
        return json.loads(raw or json.dumps(fallback))
    except (TypeError, json.JSONDecodeError):
        return fallback


def _format_bytes(value):
    if not value:
        return "0 B"
    units = ["B", "KB", "MB", "GB", "TB"]
    size = float(value)
    for unit in units:
        if size < 1024 or unit == units[-1]:
            return f"{size:.1f} {unit}" if unit != "B" else f"{int(size)} B"
        size /= 1024


def _status_hex(score):
    if score >= 70:
        return "#B91C1C"
    if score >= 35:
        return "#B45309"
    return "#047857"


def _draw_page_frame(canvas, doc):
    canvas.saveState()
    width, height = letter
    canvas.setFillColor(colors.HexColor("#0F172A"))
    canvas.rect(0, height - 0.42 * inch, width, 0.42 * inch, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(doc.leftMargin, height - 0.27 * inch, "CyberLens AI Forensic Report")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(width - doc.rightMargin, height - 0.27 * inch, f"Page {doc.page}")
    canvas.setStrokeColor(colors.HexColor("#CBD5E1"))
    canvas.line(doc.leftMargin, 0.55 * inch, width - doc.rightMargin, 0.55 * inch)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(doc.leftMargin, 0.36 * inch, "Generated by CyberLens AI. Treat this report as investigative output pending analyst review.")
    canvas.restoreState()


def _section_title(text, styles):
    return [Spacer(1, 10), Paragraph(text, styles["SectionTitle"]), HRFlowable(width="100%", color=colors.HexColor("#DBEAFE")), Spacer(1, 8)]


def _key_value_table(rows, col_widths=None):
    table = Table(rows, colWidths=col_widths or [2.0 * inch, 4.5 * inch], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#334155")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#0F172A")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#FBFDFF")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def _data_table(rows, header_color="#1D4ED8", col_widths=None):
    table = Table(rows, repeatRows=1, colWidths=col_widths, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(header_color)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def _protocol_pie_chart(protocols):
    items = sorted(protocols.items(), key=lambda item: item[1], reverse=True)[:6]
    if not items:
        return None

    drawing = Drawing(460, 210)
    drawing.add(String(0, 190, "Protocol Distribution", fontName="Helvetica-Bold", fontSize=11, fillColor=colors.HexColor("#0F172A")))
    pie = Pie()
    pie.x = 28
    pie.y = 28
    pie.width = 145
    pie.height = 145
    pie.data = [count for _, count in items]
    pie.labels = [name for name, _ in items]
    palette = ["#2563EB", "#0F766E", "#7C3AED", "#EA580C", "#DC2626", "#64748B"]
    for index, color in enumerate(palette[:len(items)]):
        pie.slices[index].fillColor = colors.HexColor(color)
    pie.slices.strokeColor = colors.white
    pie.slices.strokeWidth = 1
    drawing.add(pie)

    total = sum(count for _, count in items) or 1
    y = 158
    for index, (name, count) in enumerate(items):
        drawing.add(String(225, y, f"{name}: {count:,} packets ({(count / total) * 100:.1f}%)", fontSize=8.5, fillColor=colors.HexColor("#334155")))
        y -= 20
    return drawing


def _top_ip_bar_chart(top_src_ips):
    items = list(top_src_ips.items())[:6] if isinstance(top_src_ips, dict) else []
    if not items:
        return None

    drawing = Drawing(460, 220)
    drawing.add(String(0, 202, "Top Source IP Packet Volume", fontName="Helvetica-Bold", fontSize=11, fillColor=colors.HexColor("#0F172A")))
    chart = VerticalBarChart()
    chart.x = 36
    chart.y = 42
    chart.height = 135
    chart.width = 360
    chart.data = [[count for _, count in items]]
    chart.categoryAxis.categoryNames = [ip for ip, _ in items]
    chart.categoryAxis.labels.angle = 30
    chart.categoryAxis.labels.fontSize = 6.5
    chart.valueAxis.labels.fontSize = 7
    chart.bars[0].fillColor = colors.HexColor("#1D4ED8")
    chart.barSpacing = 2
    chart.groupSpacing = 8
    drawing.add(chart)
    return drawing


def generate_pdf(case_id, user_id, final_report_id=None):
    if has_app_context():
        app = current_app._get_current_object()
    else:
        from app import create_app
        app = create_app()
    with app.app_context():
        case = db.session.get(Case, case_id)
        user = db.session.get(User, user_id)
        final_report = db.session.get(FinalReport, final_report_id) if final_report_id else None
        if not case or not user:
            return None
        if not final_report:
            final_report = FinalReport(case_id=case_id, generated_by=user_id)
            db.session.add(final_report)
            db.session.commit()

        analysis = _latest_analysis(case_id)
        protocols = _safe_json(analysis.protocols, {}) if analysis else {}
        threats = _safe_json(analysis.threats_detected, []) if analysis else []
        src_ips = _safe_json(analysis.unique_src_ips, []) if analysis else []
        dst_ips = _safe_json(analysis.unique_dst_ips, []) if analysis else []
        top_src_ips = _safe_json(analysis.top_src_ips, {}) if analysis else {}
        top_dst_ips = _safe_json(analysis.top_dst_ips, {}) if analysis else {}
        packet_timeline = _safe_json(analysis.packet_timeline, []) if analysis else []
        ml_results = _safe_json(analysis.ml_detection_results, []) if analysis else []
        pcap_file = analysis.pcap_file if analysis else (case.pcap_files[-1] if case.pcap_files else None)
        top_protocol = max(protocols, key=protocols.get) if protocols else "N/A"
        anomaly_score = float(analysis.anomaly_score or 0.0) if analysis else 0.0

        report_dir = Path(app.config["REPORT_FOLDER"]) / str(case_id)
        report_dir.mkdir(parents=True, exist_ok=True)
        report_path = report_dir / f"{uuid.uuid4().hex}.pdf"

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(
            name="ReportTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=28,
            textColor=colors.HexColor("#0F172A"),
            spaceAfter=10,
        ))
        styles.add(ParagraphStyle(
            name="SectionTitle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#1D4ED8"),
            spaceAfter=2,
        ))
        styles.add(ParagraphStyle(
            name="SmallMuted",
            parent=styles["Normal"],
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#64748B"),
        ))
        styles.add(ParagraphStyle(
            name="Body",
            parent=styles["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
        ))

        generated_at = final_report.generated_at.strftime("%d %b %Y, %H:%M UTC")
        risk_label = "High" if anomaly_score >= 70 else "Medium" if anomaly_score >= 35 else "Low"

        story = [
            Spacer(1, 18),
            Paragraph("CyberLens AI", styles["ReportTitle"]),
            Paragraph("Professional Network Forensics & Packet Analysis Report", styles["Heading2"]),
            Spacer(1, 12),
            Table(
                [[
                    Paragraph(f"<b>Case</b><br/>{case.title}", styles["Body"]),
                    Paragraph(f"<b>Risk Level</b><br/><font color='{_status_hex(anomaly_score)}'>{risk_label}</font>", styles["Body"]),
                    Paragraph(f"<b>Generated</b><br/>{generated_at}", styles["Body"]),
                ]],
                colWidths=[3.1 * inch, 1.45 * inch, 2.0 * inch],
                hAlign="LEFT",
                style=TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
                    ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#BFDBFE")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#BFDBFE")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                    ("TOPPADDING", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ]),
            ),
            Spacer(1, 14),
            Paragraph(
                "This report summarizes uploaded packet evidence, protocol distribution, detected threats, "
                "machine-learning scan output, and chain-of-custody details for investigator review.",
                styles["Body"],
            ),
            *_section_title("Case & Evidence Summary", styles),
            _key_value_table([
                ["Investigator", user.name],
                ["Case Status", case.status.title()],
                ["Case Created", case.created_at.strftime("%d %b %Y, %H:%M UTC")],
                ["PCAP / Scanned File", pcap_file.filename if pcap_file else "No file attached"],
                ["File Size", _format_bytes(pcap_file.file_size if pcap_file else 0)],
                ["Parser Status", (pcap_file.parse_status if pcap_file else "N/A").title()],
            ]),
            *_section_title("Executive Findings", styles),
            _key_value_table([
                ["Total Packets Analyzed", f"{analysis.total_packets:,}" if analysis else "0"],
                ["Threats Identified", str(len(threats))],
                ["Anomaly Score", f"{anomaly_score:.2f}"],
                ["Top Protocol", top_protocol],
                ["Unique Source IPs", f"{len(src_ips):,}"],
                ["Unique Destination IPs", f"{len(dst_ips):,}"],
                ["Average Packet Size", f"{analysis.avg_packet_size:.2f} bytes" if analysis else "0 bytes"],
                ["Capture Duration", f"{analysis.capture_duration:.2f} seconds" if analysis else "0 seconds"],
            ]),
            PageBreak(),
            *_section_title("Threat Detection Results", styles),
        ]

        threat_rows = [["Type", "Severity", "Source IP", "Packet Count", "Notes"]]
        threat_rows.extend([
            [
                t.get("type", "N/A"),
                str(t.get("severity", "N/A")).title(),
                t.get("src_ip", "N/A"),
                t.get("packet_count", 0),
                t.get("description") or t.get("details") or "Rule/ML-based finding",
            ]
            for t in threats[:20]
        ] or [["No threats detected", "-", "-", "-", "No malicious pattern was identified in the latest scan."]])
        story.append(_data_table(threat_rows, col_widths=[1.35 * inch, 0.8 * inch, 1.25 * inch, 0.8 * inch, 2.25 * inch]))

        story.extend(_section_title("Machine Learning Scan", styles))
        ml_summary = [
            ["ML Model Status", (analysis.ml_model_status if analysis else "none").replace("_", " ").title()],
            ["Total Flows Scanned", f"{analysis.ml_total_flows:,}" if analysis else "0"],
            ["Normal Flows", f"{analysis.ml_normal_flows:,}" if analysis else "0"],
            ["Malicious Flows", f"{analysis.ml_malicious_flows:,}" if analysis else "0"],
        ]
        story.append(_key_value_table(ml_summary))
        if ml_results:
            story.append(Spacer(1, 10))
            ml_rows = [["Flow", "Prediction", "Confidence", "Source", "Destination"]]
            for index, result in enumerate(ml_results[:12], start=1):
                ml_rows.append([
                    str(result.get("flow_id", index)),
                    result.get("prediction_label") or result.get("prediction") or "N/A",
                    f"{float(result.get('confidence', 0)) * 100:.1f}%",
                    result.get("src_ip", "N/A"),
                    result.get("dst_ip", "N/A"),
                ])
            story.append(_data_table(ml_rows, header_color="#0F766E"))

        story.extend([PageBreak(), *_section_title("Packet & Protocol Analysis", styles)])
        protocol_rows = [["Protocol", "Packet Count", "Share"]]
        total_protocol_packets = sum(protocols.values()) or 1
        protocol_rows.extend([
            [protocol, f"{count:,}", f"{(count / total_protocol_packets) * 100:.1f}%"]
            for protocol, count in sorted(protocols.items(), key=lambda item: item[1], reverse=True)
        ] or [["N/A", "0", "0.0%"]])
        story.append(_data_table(protocol_rows, header_color="#334155", col_widths=[2.2 * inch, 1.4 * inch, 1.0 * inch]))
        protocol_chart = _protocol_pie_chart(protocols)
        if protocol_chart:
            story.extend([Spacer(1, 12), protocol_chart])

        story.extend(_section_title("IP Address Analysis", styles))
        ip_rows = [["Top Source IPs", "Packets", "Top Destination IPs", "Packets"]]
        source_items = list(top_src_ips.items()) if isinstance(top_src_ips, dict) else [(ip, "") for ip in src_ips[:10]]
        destination_items = list(top_dst_ips.items()) if isinstance(top_dst_ips, dict) else [(ip, "") for ip in dst_ips[:10]]
        for index in range(max(len(source_items[:10]), len(destination_items[:10]), 1)):
            src_item = source_items[index] if index < len(source_items[:10]) else ("", "")
            dst_item = destination_items[index] if index < len(destination_items[:10]) else ("", "")
            ip_rows.append([
                src_item[0],
                f"{src_item[1]:,}" if isinstance(src_item[1], int) else src_item[1],
                dst_item[0],
                f"{dst_item[1]:,}" if isinstance(dst_item[1], int) else dst_item[1],
            ])
        story.append(_data_table(ip_rows, header_color="#0F172A"))
        ip_chart = _top_ip_bar_chart(top_src_ips)
        if ip_chart:
            story.extend([Spacer(1, 12), ip_chart])

        if packet_timeline:
            story.extend(_section_title("Packet Timeline Snapshot", styles))
            timeline_rows = [["Time Bucket", "Packets"]]
            for item in packet_timeline[:12]:
                if isinstance(item, dict):
                    timeline_rows.append([item.get("time") or item.get("timestamp") or "N/A", item.get("count", 0)])
                else:
                    timeline_rows.append([str(item), ""])
            story.append(_data_table(timeline_rows, header_color="#4338CA", col_widths=[3.2 * inch, 1.1 * inch]))

        story.extend([
            PageBreak(),
            *_section_title("Chain of Custody & Analyst Sign-Off", styles),
            Paragraph(
                "This report was generated from uploaded packet capture evidence recorded in CyberLens AI. "
                "The investigator should verify source evidence integrity, packet timestamps, and all generated "
                "findings before legal, institutional, or operational submission.",
                styles["Body"],
            ),
            Spacer(1, 22),
            _key_value_table([
                ["Evidence Source", pcap_file.filename if pcap_file else "N/A"],
                ["Generated By", user.name],
                ["Report ID", str(final_report.id)],
                ["Storage Path", str(report_path)],
            ]),
            Spacer(1, 42),
            Paragraph("Investigator Signature: ______________________________", styles["Body"]),
            Spacer(1, 16),
            Paragraph("Review Date: ______________________________", styles["Body"]),
        ])

        doc = SimpleDocTemplate(
            str(report_path),
            pagesize=letter,
            rightMargin=0.55 * inch,
            leftMargin=0.55 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            title=f"CyberLens AI Forensic Report - {case.title}",
        )
        doc.build(story, onFirstPage=_draw_page_frame, onLaterPages=_draw_page_frame)
        final_report.report_path = str(report_path)
        final_report.is_court_ready = True
        db.session.commit()
        return final_report.id
