import { useState } from 'react';
import { FileText, Download, Plus, CheckCircle, Clock } from 'lucide-react';
import Badge from '../components/ui/Badge';
import Button from '../components/ui/Button';
import Modal from '../components/ui/Modal';
import Pagination from '../components/ui/Pagination';
import { reports, investigations } from '../data/dummyData';

const ITEMS_PER_PAGE = 5;

export default function Reports() {
  const [currentPage, setCurrentPage] = useState(1);
  const [showGenerate, setShowGenerate] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [selectedCase, setSelectedCase] = useState('INV-2024-001');

  const totalPages = Math.max(1, Math.ceil(reports.length / ITEMS_PER_PAGE));
  const paged = reports.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE);

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      setGenerated(true);
    }, 2000);
  };

  const resetModal = () => {
    setShowGenerate(false);
    setGenerated(false);
    setGenerating(false);
  };

  return (
    <div className="space-y-6 animate-slide-up">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Forensic Reports</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            {reports.length} reports · {reports.filter((r) => r.status === 'Final').length} finalized
          </p>
        </div>
        <Button icon={Plus} size="sm" onClick={() => setShowGenerate(true)}>
          Generate Report
        </Button>
      </div>

      {/* Summary stats */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: 'Total Reports', value: reports.length, icon: FileText, color: 'text-blue-600 bg-blue-50' },
          { label: 'Finalized', value: reports.filter((r) => r.status === 'Final').length, icon: CheckCircle, color: 'text-green-600 bg-green-50' },
          { label: 'Drafts', value: reports.filter((r) => r.status === 'Draft').length, icon: Clock, color: 'text-amber-600 bg-amber-50' },
        ].map((s) => (
          <div key={s.label} className="bg-white border border-gray-200 rounded-2xl p-5 shadow-card flex items-center gap-4">
            <div className={`w-10 h-10 rounded-xl ${s.color} flex items-center justify-center flex-shrink-0`}>
              <s.icon className="w-5 h-5" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{s.value}</p>
              <p className="text-xs text-gray-500">{s.label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="bg-white border border-gray-200 rounded-2xl shadow-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50/60">
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3">Report ID</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3">Report Name</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3 hidden md:table-cell">Case</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3 hidden lg:table-cell">Generated By</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3">Status</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3 hidden sm:table-cell">Date</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3 hidden md:table-cell">Size</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-5 py-3">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {paged.map((r) => (
                <tr key={r.id} className="hover:bg-blue-50/20 transition-colors group">
                  <td className="px-5 py-4">
                    <span className="text-xs font-mono font-semibold text-green-700 bg-green-50 px-2 py-0.5 rounded-lg">
                      {r.id}
                    </span>
                  </td>
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-lg bg-red-50 flex items-center justify-center flex-shrink-0">
                        <FileText className="w-4 h-4 text-red-500" />
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-gray-900 max-w-[220px] truncate">{r.name}</p>
                        <p className="text-xs text-gray-400">{r.pages} pages</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-5 py-4 hidden md:table-cell">
                    <span className="text-xs text-blue-600 font-semibold font-mono">{r.caseId}</span>
                  </td>
                  <td className="px-5 py-4 hidden lg:table-cell">
                    <span className="text-sm text-gray-700">{r.generatedBy}</span>
                  </td>
                  <td className="px-5 py-4"><Badge label={r.status} /></td>
                  <td className="px-5 py-4 hidden sm:table-cell">
                    <span className="text-xs text-gray-500">{r.generatedOn}</span>
                  </td>
                  <td className="px-5 py-4 hidden md:table-cell">
                    <span className="text-xs text-gray-400">{r.size}</span>
                  </td>
                  <td className="px-5 py-4">
                    <Button variant="outline" size="xs" icon={Download}>
                      PDF
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="px-5 py-3.5 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-xs text-gray-500">
            Showing {(currentPage - 1) * ITEMS_PER_PAGE + 1}–{Math.min(currentPage * ITEMS_PER_PAGE, reports.length)} of {reports.length} reports
          </p>
          <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={setCurrentPage} />
        </div>
      </div>

      {/* Generate Modal */}
      <Modal isOpen={showGenerate} onClose={resetModal} title="Generate Forensic Report">
        {!generated ? (
          <div className="space-y-5">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Select Investigation</label>
              <select
                value={selectedCase}
                onChange={(e) => setSelectedCase(e.target.value)}
                className="w-full text-sm border border-gray-200 rounded-xl px-3.5 py-2.5 bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
              >
                {investigations.map((inv) => (
                  <option key={inv.id} value={inv.id}>{inv.id} – {inv.name}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Report Sections</label>
              <div className="space-y-2">
                {[
                  'Executive Summary',
                  'Case Timeline',
                  'Packet Analysis',
                  'Threat Findings',
                  'Evidence List',
                  'Recommendations',
                ].map((s) => (
                  <label key={s} className="flex items-center gap-2.5 cursor-pointer">
                    <input
                      type="checkbox"
                      defaultChecked
                      className="w-4 h-4 rounded border-gray-300 accent-blue-600"
                    />
                    <span className="text-sm text-gray-700">{s}</span>
                  </label>
                ))}
              </div>
            </div>

            <div className="flex gap-3 pt-2">
              <Button variant="outline" onClick={resetModal} fullWidth>Cancel</Button>
              <Button
                onClick={handleGenerate}
                disabled={generating}
                fullWidth
                icon={generating ? undefined : FileText}
              >
                {generating ? (
                  <span className="flex items-center gap-2">
                    <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Generating…
                  </span>
                ) : 'Generate Report'}
              </Button>
            </div>
          </div>
        ) : (
          <div className="text-center py-4">
            <div className="w-14 h-14 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-7 h-7 text-green-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-1">Report Generated!</h3>
            <p className="text-sm text-gray-500 mb-6">Your forensic report is ready for download.</p>
            <div className="flex gap-3 justify-center">
              <Button variant="outline" onClick={resetModal}>Close</Button>
              <Button icon={Download}>Download PDF</Button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
